spring.application.name=centum

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_app
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080